name: docker_build_push_acr
 
on:
  push:
    branches: [ "development" , "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
 
jobs:
  security:
    name: SCA & SAST
    runs-on: ${{ matrix.language == 'swift' && 'macos-latest' || 'ubuntu-latest' }}
    permissions:
      actions: write
      contents: write
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ matrix.language }}"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=emergingtech-ra-org
            -Dsonar.projectKey=juice-shop-container
  trivyscan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    needs: security
    steps:
    - uses: actions/checkout@v3
    - name: Build a Docker image
      run: docker build -t demojuiceshopacr.azurecr.io/juice-app-demo .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
          image-ref: 'demojuiceshopacr.azurecr.io/juice-app-demo:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,INFO'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: 'trivy-results.sarif'
          
  build:
      name: Deploy to Azure App service
      runs-on: ubuntu-latest
      needs: trivyscan

      steps:
        - uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to container registry
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: Build and push container image to registry
          uses: docker/build-push-action@v3
          with:
            context: .
            push: true
            tags: demojuiceshopacr.azurecr.io/juice-app-demo
            file: ./Dockerfile

  deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
          name: 'production'
          url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
          - name: Deploy to Azure Web App
            id: deploy-to-webapp
            uses: azure/webapps-deploy@v2
            with:
              app-name: 'demo-juice-shop'
              slot-name: 'production'
              publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE}}
              images: 'demojuiceshopacr.azurecr.io/juice-app-demo'
